{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "schema-registry.serviceAccountName" . }}
  labels:
    {{- include "schema-registry.labels.standard" . | indent 4 }}
{{- end -}}
